### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by rpalsaxena**
This updation is required to make it work on the Windows machine for manually installing the package.

### CODE REVIEW

**Comment by Gallaecio** [comment]
It looks like you are right, if not specified the encoding is platform-dependent. If should also be used for the changes file, though, right? It probably works at the moment, but it will fail if at any point we use Unicode there.

**Comment by rpalsaxena** [comment]
Hey @Gallaecio,

Your point seems valid. Is there any other solution that we can use for windows machines?
I feel that using UTF-8, for now, can be a good choice as you guys have encoded the `README.rst` file in utf-8.
 If at any point, you plan to change the encoding to Unicode then we can change the parameter.
 
I read about the `ignore` parameter. Am not much sure about it. Do you feel that it can be helpful in our case?

**Comment by Gallaecio** [comment]
I think you are overthingking this :P

I think UTF-8 is the right choice for those files, I don’t think that will change in the foreseeable future, and `ignore` is definitely not the way to go if it can be avoided.

I would just also change `open('CHANGES.rst')` to `open('CHANGES.rst', encoding='utf-8')`, and merge.

**Comment by kmike** [comment]
Hey! I think that's fine to merge it as-is for now, because it fixes an issue. PR to make a change for CHANGELOG is welcome :) Thanks @rpalsaxena and @Gallaecio!

**Comment by kmike** [comment]
Released as 0.3.3.

**Pull request merged**
