### PR TITLE
Fix parsing price which contains non-breaking spaces

### LINKED ISSUE #39: Bug non break space.
Some store show price with non-break space and parser return None.

### PR DESCRIPTION
**Pull request by WinterComes**
Fixes #39
This PR contains changes which allow to parse prices with non-breaking space as if it is whitespace

### CODE REVIEW

**Review by lopuhin — COMMENTED** [review]
Thanks @WinterComes , the fix looks good 👍 Could you please update PR to resolve the conflicts after merge of #42 ?

**Review by lopuhin — APPROVED** [review]
Thanks @WinterComes 👍

**Comment by WinterComes** [comment]
left to wait the finish of the CI build. It was much faster year ago :slightly_smiling_face:

**Comment by lopuhin** [comment]
Yeah, the build itself is quite fast, but the queues became larger lately. Thankfully the build passed, merging, thank you!

**Comment by lopuhin** [comment]
@WinterComes do you think now it's a good time for a release, or you plan any more changes in the near future? Of cause it's not a problem to make more releases later.

**Comment by WinterComes** [comment]
> @WinterComes do you think now it's a good time for a release, or you plan any more changes in the near future? Of cause it's not a problem to make more releases later.

I think it's a good time for a release, thanks @lopuhin

**Comment by lopuhin** [comment]
0.3.4 is released now 🎉

**Pull request merged**
